version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}pizzeria-stock
    build:
      context: ./CleanCodePizzeria
      dockerfile: Dockerfile
    ports:
      - "5000:80"
  web:
    image: nginx:latest
    volumes:
      - ./web/static:/usr/share/nginx/html/
    ports:
      - "80:80"